### ISSUE TITLE
The MS-Windows code has several issues

### ISSUE THREAD

**Issue by Eli-Zaretskii** [francisco-colaco/user-directories#1]
The latest MS-Windows code in `user-directories-windows-nt.el` needs some work:

1. The Registry values it queries don't necessarily exist on older Windows versions.  For example, on XP the following keys don't exist: MyComputerFolder, Downloads, My Music, and My Videos.  As Emacs still tries to support even Windows 9X, the code should expect any key to not exist, and should provide fallbacks for those which don't.

2. Likewise with environment variables: LOCALAPPDATA exists only since Vista, so the code should provide fallback for the variables that don't exist.  (LOCALAPPDATA can default to the same directory as APPDATA, for example.)

3. `windows-shell-folder` looks up Registry values under HKCU only, but I think it's common practice to look under HKLM if not found under HKCU.

4. `window-shell-folder` calls `shell-command` in a way that assumes the shell is the stock cmd.exe or its workalike, because otherwise environment variables enclosed in percent signs, %..%, will not be expanded.  The function should make sure the command invoked is the cmd.exe built-in `echo`, not some other echo.exe that just happens to be on PATH (e.g., a port of GNU `echo`).

**Comment by francisco-colaco** [comment]
Eli,

I have made some changes.

1. If the key does not exist, then the user directory is not set.  I think there is little value in setting :downloads if Windows XP does not support it.  The user can later set it manually if he needs it with a suitable localised value.

2. Done.  If the variable LOCALAPPDATA does not exist, then APPDATA is used instead.

3. Done.  If not on HKCU, then looks up also on HKLM.

These three need testing from actual Windows Emacs users.  I tested the functions years ago, when I still booted to Windows from time to time, but at the present I only have Windows on virtual machines to run applications that do not run on Linux, and Emacs is not one of them.

4. I would be more than happy to take the two functions (windows-read-registry-value and windows-shell-folder) away and into other libraries.  But yes, we are assuming that it is cmd.exe and that has to be handled.

I will not close this issue until we tackle this situation or open another one just for number 4.

**Comment by francisco-colaco** [comment]
I have tried to use substitute-in-file-name instead of shell-command-to-string in windows-shell-folder to evaluate the environment variables.  I have tried it in Linux and does the trick.  If it works on Windows properly, maybe we can close the issue, since I guess substitute-in-file-name, defined in C, will take care of the OS implementation details.

**Comment by Eli-Zaretskii** [comment]
`substitute-in-file-name` is the right tool for the job of expanding environment variables, IMO.

**Comment by francisco-colaco** [comment]
I have made a recent commit on user-directories-windows-nt.el.  Can anyone give it a test run on Windows?

If it works, may we close this issue?

**Comment by francisco-colaco** [comment]
Having no negative feedback from the modifications in the code, despite knowing that absence of report of errors is not a report of absence, I will close the issue.

I urge everyone to test the modifications on Windows or, better, to modify the Windows code themselves.
